### ISSUE TITLE
linter

### ISSUE THREAD

**Issue by HerrMuellerluedenscheid** [HerrMuellerluedenscheid/pytch#13]
@LLDievelop @sebastianrosenzweig what is your opinion on linters? I started using [black](https://black.readthedocs.io/en/stable/) on all of my projects recently and find it super helpful. It's pretty intrusive but it enforces style and good practice. What do you think?

**Comment by sebastianrosenzweig** [comment]
This would be ok for me. @LLDievelop would you mind runnnign black over your code?

**Comment by HerrMuellerluedenscheid** [comment]
Cool. Let's have this in a separate merge request, not in #12.

**Comment by LLDievelop** [comment]
Yes, no problem. What is the workflow for black?

**Comment by HerrMuellerluedenscheid** [comment]
> Yes, no problem. What is the workflow for black?

Install it, run it with `black`. You can provide individual files as input to black if you want to first try it. If no input args are provided it will work though all sub-directories.

Let me prepare same helper `Makefile` to facilitate the linting.

**Comment by LLDievelop** [comment]
I just ran black out-of-the-box over the source files, and it seems it mostly replaces single quotes (') with double quotes ("), which leads to many (unnecessary?) changes as single quotes are used quite consistently in the project. Does the `Makefile` prevent this?

**Comment by HerrMuellerluedenscheid** [comment]
> I just ran black out-of-the-box over the source files, and it seems it mostly replaces single quotes (') with double quotes ("), which leads to many (unnecessary?) changes as single quotes are used quite consistently in the project. Does the `Makefile` prevent this?

My experience of the last 6 months or so is that automated style linting simply reduces discussion on style, especially when collaborating. It may take a minute or two to get used to single vs double quotes but the benefit of an automated linter is simply less time spent on discussing style. So, I think it's worth going with the double quotes.

Check the MR #15. `pre-commit` is an awesome tool that will check style on each commit to enforce permanent consistent style. Helps a lot!

**Comment by HerrMuellerluedenscheid** [comment]
Implemented in #15
